# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: cbef920856692b11632fe2457b7d278a5c74cacf6aa565aae3829b4646376d520f2e4abfe4035587dcc429ecd0915f9c466b95104a22fd4874ae0979633ca012

test:
  secret_key_base: 8e1139b67ae2160c1f816d667c8eefbb3dd612f9a15c48c75a89ad5ae0eb8e476716daff900dca863b7d73878ff504ba49f3efedea6f49de7281d87887009b77

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
